import { normalizeDigits, toPersianDigits } from './digits';

export interface NationalCodeInfo {
  code: string;
  isValid: boolean;
  formatted: string;
  masked: string;
  province: ProvinceInfo | null;
}

export interface ProvinceInfo {
  code: string;
  province: string;
  city: string;
}

const PROVINCE_CODES: Record<string, ProvinceInfo> = {
  '001': { code: '001', province: 'تهران', city: 'تهران مرکزی' },
  '002': { code: '002', province: 'تهران', city: 'تهران مرکزی' },
  '003': { code: '003', province: 'تهران', city: 'تهران مرکزی' },
  '004': { code: '004', province: 'تهران', city: 'تهران مرکزی' },
  '005': { code: '005', province: 'تهران', city: 'تهران مرکزی' },
  '006': { code: '006', province: 'تهران', city: 'تهران مرکزی' },
  '007': { code: '007', province: 'تهران', city: 'تهران' },
  '008': { code: '008', province: 'تهران', city: 'تهران' },
  '011': { code: '011', province: 'تهران', city: 'تهران جنوب' },
  '015': { code: '015', province: 'تهران', city: 'تهران غرب' },
  '020': { code: '020', province: 'تهران', city: 'تهران شرق' },
  '025': { code: '025', province: 'تهران', city: 'تهران شمال' },
  '031': { code: '031', province: 'البرز', city: 'کرج' },
  '032': { code: '032', province: 'البرز', city: 'کرج' },
  '041': { code: '041', province: 'تهران', city: 'ورامین' },
  '042': { code: '042', province: 'تهران', city: 'ورامین' },
  '043': { code: '043', province: 'تهران', city: 'دماوند' },
  '044': { code: '044', province: 'تهران', city: 'شمیران' },
  '045': { code: '045', province: 'تهران', city: 'شمیران' },
  '048': { code: '048', province: 'تهران', city: 'شهرری' },
  '049': { code: '049', province: 'تهران', city: 'شهرری' },
  '051': { code: '051', province: 'مرکزی', city: 'آشتیان' },
  '052': { code: '052', province: 'مرکزی', city: 'اراک' },
  '053': { code: '053', province: 'مرکزی', city: 'اراک' },
  '055': { code: '055', province: 'مرکزی', city: 'خمین' },
  '056': { code: '056', province: 'مرکزی', city: 'محلات' },
  '057': { code: '057', province: 'مرکزی', city: 'دلیجان' },
  '058': { code: '058', province: 'مرکزی', city: 'تفرش' },
  '059': { code: '059', province: 'مرکزی', city: 'ساوه' },
  '060': { code: '060', province: 'مرکزی', city: 'ساوه' },
  '061': { code: '061', province: 'مرکزی', city: 'سربند' },
  '062': { code: '062', province: 'مرکزی', city: 'سربند' },
  '063': { code: '063', province: 'خراسان شمالی', city: 'اسفراین' },
  '064': { code: '064', province: 'خراسان جنوبی', city: 'بیرجند' },
  '065': { code: '065', province: 'خراسان جنوبی', city: 'بیرجند' },
  '067': { code: '067', province: 'خراسان شمالی', city: 'بجنورد' },
  '068': { code: '068', province: 'خراسان شمالی', city: 'بجنورد' },
  '069': { code: '069', province: 'خراسان رضوی', city: 'تربت حیدریه' },
  '070': { code: '070', province: 'خراسان رضوی', city: 'تربت حیدریه' },
  '072': { code: '072', province: 'خراسان رضوی', city: 'تربت جام' },
  '073': { code: '073', province: 'خراسان رضوی', city: 'تربت جام' },
  '074': { code: '074', province: 'خراسان رضوی', city: 'تایباد' },
  '075': { code: '075', province: 'خراسان شمالی', city: 'جاجرم' },
  '076': { code: '076', province: 'خراسان رضوی', city: 'خواف' },
  '077': { code: '077', province: 'خراسان رضوی', city: 'درگز' },
  '078': { code: '078', province: 'خراسان رضوی', city: 'سبزوار' },
  '079': { code: '079', province: 'خراسان رضوی', city: 'سبزوار' },
  '081': { code: '081', province: 'خراسان رضوی', city: 'سرخس' },
  '082': { code: '082', province: 'خراسان شمالی', city: 'شیروان' },
  '083': { code: '083', province: 'خراسان جنوبی', city: 'طبس' },
  '084': { code: '084', province: 'خراسان رضوی', city: 'فریمان' },
  '085': { code: '085', province: 'خراسان جنوبی', city: 'فردوس' },
  '086': { code: '086', province: 'خراسان رضوی', city: 'قوچان' },
  '087': { code: '087', province: 'خراسان رضوی', city: 'قوچان' },
  '088': { code: '088', province: 'خراسان جنوبی', city: 'قائنات' },
  '089': { code: '089', province: 'خراسان رضوی', city: 'کاشمر' },
  '090': { code: '090', province: 'خراسان رضوی', city: 'کاشمر' },
  '091': { code: '091', province: 'خراسان رضوی', city: 'گناباد' },
  '092': { code: '092', province: 'خراسان رضوی', city: 'مشهد' },
  '093': { code: '093', province: 'خراسان رضوی', city: 'مشهد' },
  '094': { code: '094', province: 'خراسان رضوی', city: 'مشهد' },
  '096': { code: '096', province: 'خراسان رضوی', city: 'مشهد منطقه۱' },
  '097': { code: '097', province: 'خراسان رضوی', city: 'مشهد منطقه۲' },
  '098': { code: '098', province: 'خراسان رضوی', city: 'مشهد منطقه۳' },
  '105': { code: '105', province: 'خراسان رضوی', city: 'نیشابور' },
  '106': { code: '106', province: 'خراسان رضوی', city: 'نیشابور' },
  '108': { code: '108', province: 'اصفهان', city: 'نجف آباد' },
  '109': { code: '109', province: 'اصفهان', city: 'نجف آباد' },
  '110': { code: '110', province: 'اصفهان', city: 'فلاورجان' },
  '111': { code: '111', province: 'اصفهان', city: 'فلاورجان' },
  '112': { code: '112', province: 'اصفهان', city: 'فریدونشهر' },
  '113': { code: '113', province: 'اصفهان', city: 'خمینی شهر' },
  '114': { code: '114', province: 'اصفهان', city: 'خمینی شهر' },
  '115': { code: '115', province: 'اصفهان', city: 'فریدن' },
  '116': { code: '116', province: 'اصفهان', city: 'لنجان' },
  '117': { code: '117', province: 'اصفهان', city: 'لنجان' },
  '118': { code: '118', province: 'اصفهان', city: 'اردستان' },
  '119': { code: '119', province: 'اصفهان', city: 'شهرضا' },
  '120': { code: '120', province: 'اصفهان', city: 'سمیرم' },
  '121': { code: '121', province: 'اصفهان', city: 'گلپایگان' },
  '122': { code: '122', province: 'اصفهان', city: 'خوانسار' },
  '123': { code: '123', province: 'اصفهان', city: 'نطنز' },
  '124': { code: '124', province: 'اصفهان', city: 'نائین' },
  '125': { code: '125', province: 'اصفهان', city: 'کاشان' },
  '126': { code: '126', province: 'اصفهان', city: 'کاشان' },
  '127': { code: '127', province: 'اصفهان', city: 'اصفهان' },
  '128': { code: '128', province: 'اصفهان', city: 'اصفهان' },
  '129': { code: '129', province: 'اصفهان', city: 'اصفهان' },
  '136': { code: '136', province: 'آذربایجان شرقی', city: 'تبریز' },
  '137': { code: '137', province: 'آذربایجان شرقی', city: 'تبریز' },
  '138': { code: '138', province: 'آذربایجان شرقی', city: 'تبریز' },
  '145': { code: '145', province: 'اردبیل', city: 'اردبیل' },
  '146': { code: '146', province: 'اردبیل', city: 'اردبیل' },
  '149': { code: '149', province: 'آذربایجان شرقی', city: 'اهر' },
  '150': { code: '150', province: 'آذربایجان شرقی', city: 'اهر' },
  '152': { code: '152', province: 'آذربایجان شرقی', city: 'میانه' },
  '153': { code: '153', province: 'آذربایجان شرقی', city: 'میانه' },
  '154': { code: '154', province: 'آذربایجان شرقی', city: 'مراغه' },
  '155': { code: '155', province: 'آذربایجان شرقی', city: 'مراغه' },
  '158': { code: '158', province: 'آذربایجان شرقی', city: 'مرند' },
  '159': { code: '159', province: 'آذربایجان شرقی', city: 'هشترود' },
  '160': { code: '160', province: 'آذربایجان شرقی', city: 'هشترود' },
  '161': { code: '161', province: 'اردبیل', city: 'مغان' },
  '162': { code: '162', province: 'اردبیل', city: 'مغان' },
  '163': { code: '163', province: 'اردبیل', city: 'خلخال' },
  '164': { code: '164', province: 'آذربایجان شرقی', city: 'سراب' },
  '165': { code: '165', province: 'آذربایجان شرقی', city: 'سراب' },
  '166': { code: '166', province: 'اردبیل', city: 'مشکین شهر' },
  '167': { code: '167', province: 'اردبیل', city: 'مشکین شهر' },
  '168': { code: '168', province: 'آذربایجان شرقی', city: 'بناب' },
  '169': { code: '169', province: 'آذربایجان شرقی', city: 'آذرشهر' },
  '170': { code: '170', province: 'آذربایجان شرقی', city: 'اسکو' },
  '171': { code: '171', province: 'آذربایجان شرقی', city: 'بستان آباد' },
  '172': { code: '172', province: 'آذربایجان شرقی', city: 'شبستر' },
  '173': { code: '173', province: 'آذربایجان شرقی', city: 'هریس' },
  '174': { code: '174', province: 'خوزستان', city: 'اهواز' },
  '175': { code: '175', province: 'خوزستان', city: 'اهواز' },
  '181': { code: '181', province: 'خوزستان', city: 'آبادان' },
  '182': { code: '182', province: 'خوزستان', city: 'خرمشهر' },
  '183': { code: '183', province: 'خوزستان', city: 'ایذه' },
  '184': { code: '184', province: 'خوزستان', city: 'ایذه' },
  '185': { code: '185', province: 'خوزستان', city: 'بهبهان' },
  '186': { code: '186', province: 'خوزستان', city: 'بهبهان' },
  '187': { code: '187', province: 'خوزستان', city: 'شوشتر' },
  '188': { code: '188', province: 'خوزستان', city: 'شوشتر' },
  '189': { code: '189', province: 'خوزستان', city: 'شادگان' },
  '190': { code: '190', province: 'خوزستان', city: 'رامهرمز' },
  '191': { code: '191', province: 'خوزستان', city: 'رامهرمز' },
  '192': { code: '192', province: 'خوزستان', city: 'اندیمشک' },
  '193': { code: '193', province: 'خوزستان', city: 'اندیمشک' },
  '194': { code: '194', province: 'خوزستان', city: 'بندرماهشهر' },
  '195': { code: '195', province: 'خوزستان', city: 'بندرماهشهر' },
  '196': { code: '196', province: 'خوزستان', city: 'مسجدسلیمان' },
  '197': { code: '197', province: 'خوزستان', city: 'مسجدسلیمان' },
  '198': { code: '198', province: 'خوزستان', city: 'دشت آزادگان' },
  '199': { code: '199', province: 'خوزستان', city: 'دزفول' },
  '200': { code: '200', province: 'خوزستان', city: 'دزفول' },
  '202': { code: '202', province: 'گلستان', city: 'گنبد کاووس' },
  '203': { code: '203', province: 'گلستان', city: 'گنبد کاووس' },
  '205': { code: '205', province: 'مازندران', city: 'بابل' },
  '206': { code: '206', province: 'مازندران', city: 'بابل' },
  '208': { code: '208', province: 'مازندران', city: 'ساری' },
  '209': { code: '209', province: 'مازندران', city: 'ساری' },
  '211': { code: '211', province: 'گلستان', city: 'گرگان' },
  '212': { code: '212', province: 'گلستان', city: 'گرگان' },
  '213': { code: '213', province: 'مازندران', city: 'آمل' },
  '214': { code: '214', province: 'مازندران', city: 'آمل' },
  '215': { code: '215', province: 'مازندران', city: 'قائمشهر' },
  '216': { code: '216', province: 'مازندران', city: 'قائمشهر' },
  '217': { code: '217', province: 'مازندران', city: 'بهشهر' },
  '218': { code: '218', province: 'مازندران', city: 'بهشهر' },
  '219': { code: '219', province: 'مازندران', city: 'نوشهر' },
  '220': { code: '220', province: 'مازندران', city: 'نوشهر' },
  '221': { code: '221', province: 'مازندران', city: 'تنکابن' },
  '222': { code: '222', province: 'مازندران', city: 'نور' },
  '223': { code: '223', province: 'گلستان', city: 'بندرترکمن' },
  '224': { code: '224', province: 'گلستان', city: 'کردکوی' },
  '225': { code: '225', province: 'مازندران', city: 'سوادکوه' },
  '226': { code: '226', province: 'گلستان', city: 'علی آباد' },
  '227': { code: '227', province: 'مازندران', city: 'رامسر' },
  '228': { code: '228', province: 'فارس', city: 'شیراز' },
  '229': { code: '229', province: 'فارس', city: 'شیراز' },
  '230': { code: '230', province: 'فارس', city: 'شیراز' },
  '236': { code: '236', province: 'فارس', city: 'کازرون' },
  '237': { code: '237', province: 'فارس', city: 'کازرون' },
  '238': { code: '238', province: 'فارس', city: 'ممسنی' },
  '239': { code: '239', province: 'فارس', city: 'ممسنی' },
  '242': { code: '242', province: 'فارس', city: 'مرودشت' },
  '243': { code: '243', province: 'فارس', city: 'مرودشت' },
  '244': { code: '244', province: 'فارس', city: 'فیروزآباد' },
  '245': { code: '245', province: 'فارس', city: 'فیروزآباد' },
  '248': { code: '248', province: 'فارس', city: 'داراب' },
  '249': { code: '249', province: 'فارس', city: 'داراب' },
  '250': { code: '250', province: 'فارس', city: 'لارستان' },
  '251': { code: '251', province: 'فارس', city: 'لارستان' },
  '253': { code: '253', province: 'فارس', city: 'سپیدان' },
  '255': { code: '255', province: 'فارس', city: 'نی ریز' },
  '256': { code: '256', province: 'فارس', city: 'فسا' },
  '257': { code: '257', province: 'فارس', city: 'فسا' },
  '258': { code: '258', province: 'گیلان', city: 'رشت' },
  '259': { code: '259', province: 'گیلان', city: 'رشت' },
  '261': { code: '261', province: 'گیلان', city: 'آستارا' },
  '262': { code: '262', province: 'گیلان', city: 'طالش' },
  '263': { code: '263', province: 'گیلان', city: 'طالش' },
  '264': { code: '264', province: 'گیلان', city: 'بندرانزلی' },
  '265': { code: '265', province: 'گیلان', city: 'رودبار' },
  '266': { code: '266', province: 'گیلان', city: 'فومن' },
  '267': { code: '267', province: 'گیلان', city: 'صومعه سرا' },
  '268': { code: '268', province: 'گیلان', city: 'رودسر' },
  '269': { code: '269', province: 'گیلان', city: 'رودسر' },
  '270': { code: '270', province: 'گیلان', city: 'لنگرود' },
  '271': { code: '271', province: 'گیلان', city: 'لاهیجان' },
  '272': { code: '272', province: 'گیلان', city: 'لاهیجان' },
  '273': { code: '273', province: 'گیلان', city: 'آستانه' },
  '274': { code: '274', province: 'آذربایجان غربی', city: 'ارومیه' },
  '275': { code: '275', province: 'آذربایجان غربی', city: 'ارومیه' },
  '279': { code: '279', province: 'آذربایجان غربی', city: 'خوی' },
  '280': { code: '280', province: 'آذربایجان غربی', city: 'خوی' },
  '282': { code: '282', province: 'آذربایجان غربی', city: 'ماکو' },
  '283': { code: '283', province: 'آذربایجان غربی', city: 'ماکو' },
  '284': { code: '284', province: 'آذربایجان غربی', city: 'سلماس' },
  '285': { code: '285', province: 'آذربایجان غربی', city: 'سلماس' },
  '286': { code: '286', province: 'آذربایجان غربی', city: 'مهاباد' },
  '287': { code: '287', province: 'آذربایجان غربی', city: 'مهاباد' },
  '288': { code: '288', province: 'آذربایجان غربی', city: 'سردشت' },
  '289': { code: '289', province: 'آذربایجان غربی', city: 'پیرانشهر' },
  '290': { code: '290', province: 'آذربایجان غربی', city: 'نقده' },
  '291': { code: '291', province: 'آذربایجان غربی', city: 'سیه چشمه' },
  '292': { code: '292', province: 'آذربایجان غربی', city: 'بوکان' },
  '293': { code: '293', province: 'آذربایجان غربی', city: 'شاهین دژ' },
  '294': { code: '294', province: 'آذربایجان غربی', city: 'تکاب' },
  '295': { code: '295', province: 'آذربایجان غربی', city: 'اشنویه' },
  '296': { code: '296', province: 'آذربایجان غربی', city: 'میاندوآب' },
  '297': { code: '297', province: 'آذربایجان غربی', city: 'میاندوآب' },
  '322': { code: '322', province: 'کرمانشاه', city: 'پاوه' },
  '323': { code: '323', province: 'کرمانشاه', city: 'پاوه' },
  '324': { code: '324', province: 'کرمانشاه', city: 'کرمانشاه' },
  '325': { code: '325', province: 'کرمانشاه', city: 'کرمانشاه' },
  '330': { code: '330', province: 'کرمانشاه', city: 'کنگاور' },
  '331': { code: '331', province: 'کرمانشاه', city: 'هرسین' },
  '332': { code: '332', province: 'کرمانشاه', city: 'گیلانغرب' },
  '333': { code: '333', province: 'کرمانشاه', city: 'اسلام آباد' },
  '334': { code: '334', province: 'کرمانشاه', city: 'اسلام آباد' },
  '335': { code: '335', province: 'کرمانشاه', city: 'سنقر' },
  '336': { code: '336', province: 'کرمانشاه', city: 'سرپل ذهاب' },
  '337': { code: '337', province: 'کرمانشاه', city: 'قصرشیرین' },
  '338': { code: '338', province: 'هرمزگان', city: 'بندرعباس' },
  '339': { code: '339', province: 'هرمزگان', city: 'بندرعباس' },
  '341': { code: '341', province: 'هرمزگان', city: 'میناب' },
  '342': { code: '342', province: 'هرمزگان', city: 'میناب' },
  '343': { code: '343', province: 'هرمزگان', city: 'بندرلنگه' },
  '344': { code: '344', province: 'هرمزگان', city: 'بندرلنگه' },
  '345': { code: '345', province: 'هرمزگان', city: 'قشم' },
  '346': { code: '346', province: 'هرمزگان', city: 'جاسک' },
  '348': { code: '348', province: 'هرمزگان', city: 'بستک' },
  '349': { code: '349', province: 'بوشهر', city: 'بوشهر' },
  '350': { code: '350', province: 'بوشهر', city: 'بوشهر' },
  '351': { code: '351', province: 'بوشهر', city: 'دشتستان' },
  '352': { code: '352', province: 'بوشهر', city: 'دشتستان' },
  '353': { code: '353', province: 'بوشهر', city: 'بندر گناوه' },
  '354': { code: '354', province: 'بوشهر', city: 'دشتی' },
  '355': { code: '355', province: 'بوشهر', city: 'تنگستان' },
  '356': { code: '356', province: 'بوشهر', city: 'کنگان' },
  '357': { code: '357', province: 'بوشهر', city: 'دیر' },
  '358': { code: '358', province: 'سیستان و بلوچستان', city: 'ایرانشهر' },
  '359': { code: '359', province: 'سیستان و بلوچستان', city: 'ایرانشهر' },
  '361': { code: '361', province: 'سیستان و بلوچستان', city: 'زاهدان' },
  '362': { code: '362', province: 'سیستان و بلوچستان', city: 'زاهدان' },
  '364': { code: '364', province: 'سیستان و بلوچستان', city: 'چابهار' },
  '365': { code: '365', province: 'سیستان و بلوچستان', city: 'چابهار' },
  '366': { code: '366', province: 'سیستان و بلوچستان', city: 'زابل' },
  '367': { code: '367', province: 'سیستان و بلوچستان', city: 'زابل' },
  '369': { code: '369', province: 'سیستان و بلوچستان', city: 'سراوان' },
  '370': { code: '370', province: 'سیستان و بلوچستان', city: 'سراوان' },
  '371': { code: '371', province: 'سیستان و بلوچستان', city: 'خاش' },
  '386': { code: '386', province: 'همدان', city: 'همدان' },
  '387': { code: '387', province: 'همدان', city: 'همدان' },
  '392': { code: '392', province: 'همدان', city: 'ملایر' },
  '393': { code: '393', province: 'همدان', city: 'ملایر' },
  '394': { code: '394', province: 'کرمانشاه', city: 'کرند' },
  '395': { code: '395', province: 'کرمانشاه', city: 'جوانرود' },
  '396': { code: '396', province: 'همدان', city: 'نهاوند' },
  '397': { code: '397', province: 'همدان', city: 'تویسرکان' },
  '398': { code: '398', province: 'همدان', city: 'رزن' },
  '399': { code: '399', province: 'همدان', city: 'رزن' },
  '400': { code: '400', province: 'همدان', city: 'اسدآباد' },
  '401': { code: '401', province: 'همدان', city: 'اسدآباد' },
  '402': { code: '402', province: 'همدان', city: 'کبودرآهنگ' },
  '403': { code: '403', province: 'همدان', city: 'کبودرآهنگ' },
  '404': { code: '404', province: 'همدان', city: 'بهار' },
  '405': { code: '405', province: 'همدان', city: 'بهار' },
  '406': { code: '406', province: 'لرستان', city: 'خرم آباد' },
  '407': { code: '407', province: 'لرستان', city: 'خرم آباد' },
  '412': { code: '412', province: 'لرستان', city: 'بروجرد' },
  '413': { code: '413', province: 'لرستان', city: 'بروجرد' },
  '416': { code: '416', province: 'لرستان', city: 'الیگودرز' },
  '417': { code: '417', province: 'لرستان', city: 'الیگودرز' },
  '418': { code: '418', province: 'لرستان', city: 'الشتر' },
  '419': { code: '419', province: 'لرستان', city: 'کوهدشت' },
  '420': { code: '420', province: 'لرستان', city: 'نورآباد' },
  '421': { code: '421', province: 'لرستان', city: 'دورود' },
  '422': { code: '422', province: 'کهگیلویه و بویراحمد', city: 'یاسوج' },
  '423': { code: '423', province: 'کهگیلویه و بویراحمد', city: 'یاسوج' },
  '424': { code: '424', province: 'کهگیلویه و بویراحمد', city: 'دهدشت' },
  '425': { code: '425', province: 'کهگیلویه و بویراحمد', city: 'دهدشت' },
  '426': { code: '426', province: 'کهگیلویه و بویراحمد', city: 'گچساران' },
  '427': { code: '427', province: 'زنجان', city: 'زنجان' },
  '428': { code: '428', province: 'زنجان', city: 'زنجان' },
  '442': { code: '442', province: 'یزد', city: 'یزد' },
  '443': { code: '443', province: 'یزد', city: 'یزد' },
  '444': { code: '444', province: 'یزد', city: 'اردکان' },
  '445': { code: '445', province: 'یزد', city: 'تفت' },
  '446': { code: '446', province: 'یزد', city: 'مهریز' },
  '447': { code: '447', province: 'یزد', city: 'بافق' },
  '448': { code: '448', province: 'یزد', city: 'میبد' },
  '449': { code: '449', province: 'ایلام', city: 'ایلام' },
  '450': { code: '450', province: 'ایلام', city: 'ایلام' },
  '451': { code: '451', province: 'ایلام', city: 'دهلران' },
  '452': { code: '452', province: 'ایلام', city: 'مهران' },
  '453': { code: '453', province: 'ایلام', city: 'شیروان و چرداول' },
  '454': { code: '454', province: 'ایلام', city: 'آبدانان' },
  '455': { code: '455', province: 'ایلام', city: 'دره شهر' },
  '456': { code: '456', province: 'سمنان', city: 'سمنان' },
  '457': { code: '457', province: 'سمنان', city: 'دامغان' },
  '458': { code: '458', province: 'سمنان', city: 'شاهرود' },
  '459': { code: '459', province: 'سمنان', city: 'شاهرود' },
  '460': { code: '460', province: 'سمنان', city: 'گرمسار' },
  '461': { code: '461', province: 'چهارمحال و بختیاری', city: 'شهرکرد' },
  '462': { code: '462', province: 'چهارمحال و بختیاری', city: 'شهرکرد' },
  '465': { code: '465', province: 'چهارمحال و بختیاری', city: 'بروجن' },
  '466': { code: '466', province: 'چهارمحال و بختیاری', city: 'لردگان' },
  '467': { code: '467', province: 'چهارمحال و بختیاری', city: 'فارسان' },
  '468': { code: '468', province: 'چهارمحال و بختیاری', city: 'اردل' },
  '469': { code: '469', province: 'هرمزگان', city: 'رودان' },
  '470': { code: '470', province: 'هرمزگان', city: 'گاوبندی' },
  '471': { code: '471', province: 'امور خارجه', city: 'امور خارجه' },
  '472': { code: '472', province: 'امور خارجه', city: 'امور خارجه' },
  '507': { code: '507', province: 'آذربایجان شرقی', city: 'ملکان' },
};

export const validateIranianNationalCode = (code: string): boolean => {
  if (!/^\d{10}$/.test(code)) return false;
  if (/^(\d)\1{9}$/.test(code)) return false;

  const check = +code[9];
  const sum = code
    .split('')
    .slice(0, 9)
    .reduce((acc, digit, index) => acc + +digit * (10 - index), 0);

  const remainder = sum % 11;

  return (
    (remainder < 2 && check === remainder) ||
    (remainder >= 2 && check === 11 - remainder)
  );
};

export const maskNationalCode = (code: string): string =>
  `${code.slice(0, 3)}***${code.slice(6)}`;

export const formatNationalCode = (code: string): string =>
  `${code.slice(0, 3)}-${code.slice(3, 6)}-${code.slice(6)}`;

export const normalizeNationalCode = (code: string): string => {
  const digits = normalizeDigits(code).replace(/\D/g, '');
  return digits.padStart(10, '0');
};

export const getProvinceByNationalCode = (code: string): ProvinceInfo | null => {
  const normalized = normalizeNationalCode(code);
  const prefix = normalized.slice(0, 3);
  return PROVINCE_CODES[prefix] ?? null;
};

export const toPersianNationalCode = (code: string): string =>
  toPersianDigits(normalizeNationalCode(code));

export const isSameNationalCode = (a: string, b: string): boolean =>
  normalizeNationalCode(a) === normalizeNationalCode(b);

export const isRepeatedDigits = (code: string): boolean =>
  /^(\d)\1{9}$/.test(normalizeNationalCode(code));

export const extractNationalCodes = (text: string): string[] => {
  const normalized = normalizeDigits(text);
  const matches = normalized.match(/\b\d{10}\b/g) ?? [];
  return [...new Set(matches.filter(validateIranianNationalCode))];
};

export const getNationalCodeInfo = (code: string): NationalCodeInfo => {
  const normalized = normalizeNationalCode(code);
  const isValid = validateIranianNationalCode(normalized);

  return {
    code: normalized,
    isValid,
    formatted: formatNationalCode(normalized),
    masked: maskNationalCode(normalized),
    province: isValid ? getProvinceByNationalCode(normalized) : null,
  };
};